- name: Disable default nginx
  ansible.builtin.command: dnf module disable nginx -y
- name: Enable required nginx module
  ansible.builtin.command: dnf module enable nginx:1.24 -y
- name: Install nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: Start and Enable nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: Clean default nginx content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent
- name: Create html directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: download roboshop frontend content
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
    dest: /tmp/frontend.zip

- name: Extract frontend content
  ansible.builtin.unarchive:
    src: /tmp/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: remove default nginx conf
  ansible.builtin.file:
    path: /etc/nginx/nginx.conf
    state: absent

- name: copy roboshop nginx conf
  ansible.builtin.copy:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - Restart nginx

