- name: Disable default nodejs module
  ansible.builtin.command: dnf module disable nodejs -y
- name: Enable required nodejs module
  ansible.builtin.command: dnf module enable nodejs:20 -y
- name: Install nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: present
- name: Install npm dependencies
  ansible.builtin.command: npm install
  args:
    chdir: /app
