- name: Install Python, build tools, SSH, and SSL packages
  ansible.builtin.dnf:
    name:
      - python3
      - gcc
      - python3-devel
    state: present
    update_cache: yes

- name: Install python dependencies
  ansible.builtin.pip:
    requirements: /app/requirements.txt
    executable: pip3.9