- name: Copy systemd service file
  ansible.builtin.template:
    src: ' {{ component }}.service.j2'
    dest: '/etc/systemd/system/{{ component}}.service'
    remote_src: yes

- name: System deamon reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: Start and Enable {{ component }} service
  ansible.builtin.service:
    name: '{{ component }}'
    state: restarted
    enabled: yes
